export const ADD_USERS = 'ADD_USERS';
export const LOGIN_USER = 'LOGIN_USER';
export const SELECT_USER = 'SELECT_USER';
export const REMOVE_SELECTED_USER = 'REMOVE_SELECTED_USER';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
